# This is an example playbook. Run it with
#     ansible-playbook -i hosts.example example.yml
- hosts: hyperfoil_controller
  roles:
  - hyperfoil.hyperfoil_setup
  - hyperfoil.hyperfoil_test
  vars:
    test_name: example
- hosts: hyperfoil_controller
  tasks:
  - name: Find number of requests
    set_fact:
      test_requests: "{{ lookup('csvfile', 'example file=/tmp/hyperfoil/workspace/run/' + test_runid + '/stats/total.csv col=2 delimiter=,')}}"
  - name: Print number of requests
    debug:
      msg: "Executed {{ test_requests }} requests."
- hosts:
  - hyperfoil_controller
  roles:
  - hyperfoil.hyperfoil_shutdown